### ISSUE TITLE
Support tar archives?

### ISSUE THREAD

**Issue by lurch** [balena-io-modules/etcher-image-stream#41]
Given that etcher-image-stream already supports `.zip` archives, would it be worth adding support for `.tar`, `.tar.gz`, `.tar.xz` etc. archives too? In theory `.tar.xz` can support better compression than `.zip`.

Probably wouldn't hurt to add `.7z` support either? (which I believe is more [popular](https://sourceforge.net/p/sevenzip/discussion/45797/thread/920f3324/) on Windows than `.xz`)

Might also be useful for `README.md` to explicitly list the currently supported file formats?

**Comment by jviotti** [comment]
Hi @lurch ,

Adding support for an "archive" format is just a matter of implementing two functions for it: `.getEntries()` and `.extractFile()`. See [the current zip implementation](https://github.com/resin-io-modules/etcher-image-stream/blob/master/lib/archive-hooks/zip.js) if you want to give it a shot yourself.

> Probably wouldn't hurt to add .7z support either? (which I believe is more popular on Windows than .xz)

Regarding 7z, we're tracking this feature in https://github.com/resin-io/etcher/issues/711. The problem is that there is no decent third party module implementing support for it. There are many on the internet that just call `7z` as a child process.

**Comment by jviotti** [comment]
> Might also be useful for README.md to explicitly list the currently supported file formats?

It'd be sweet if we can generate this automatically using JSDoc or something like that.

**Comment by lurch** [comment]
> It'd be sweet if we can generate this automatically using JSDoc or something like that.

\*shrug\* I've never even heard of JSDoc.

**Comment by lurch** [comment]
> See the current zip implementation if you want to give it a shot yourself.

Haha, that's advanced Javascript that I can't even _read_ yet, let alone write! :laughing:
